#+TITLE: cybernest-xd
#+AUTHOR: v3ga jerusalem
#+STARTUP: hidestars

Cybernest is a personal database and playground to learn as well as capture things that I like
Journaling, Task Management, Fitness, Books, possibly bookmark manager


So lets get going transferring pieces from old project.
What do you want to do here? This won't be public facing so have fun with is/

I should be able to read .org, & .md files as well as make posts that are saved in the database
* Todays Agenda
** Reitit POST with json



* Backburner Agenda
** DOING review 'coercion'


* Completion List
** TODO start connection pool and pass in source to routes via integrant




* Ideas
  futura font
  animated raining header at some points? javascript project?
  90% max-width 2400?

* Sections [0/4]
** DOING Iotas and Thoughts
** DOING [#A] Grand Station (notes/thoughts/timeline... this will actually be a timeline to pull in all of my stuff together.)
** TODO [#B] Book Shelf
** TODO [#B] Errol or Neptune - XSS Reader/Bookmarks  (this section WILL be neptune blue...)
** TODO [#C] Fuel (fitness goals/progress pics)



* Start DB
  postgres -D /usr/local/var/postgres



* Useful links
  https://ghufran.posthaven.com/setting-up-a-reagent-clojurescript-project-with-shadow-cljs-and-cursive



* Shadow-cljs choose cider-connect then :app, fyi make sure main server is up and running
** Sesman browser to see what repls are running. clj&cljs jack-in works now
  #+BEGIN_SRC clojure
(do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/nrepl-select :app))
  #+END_SRC
